# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 17:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Choir',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(default='Best Choir in the World', max_length=100)),
                ('director', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('group_user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FlashCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('front', models.CharField(max_length=500)),
                ('back', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('title', models.CharField(max_length=100)),
                ('choir', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorize.Choir')),
            ],
        ),
        migrations.AddField(
            model_name='flashcard',
            name='song',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memorize.Song'),
        ),
    ]
