# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-07 20:43
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choir',
            name='group_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
