# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 00:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0003_auto_20171207_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flashcard',
            name='song',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='memorize.Song'),
        ),
    ]
