# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-12-13 00:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memorize', '0004_auto_20171213_0033'),
    ]

    operations = [
        migrations.AddField(
            model_name='choir',
            name='password',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
